name: Maven Build & Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build and Test
        run: mvn clean install
        working-directory: .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-app
          path: src/main/webapp/target/*.war  # Adjust for JAR/WAR files
